# -*- coding: utf-8 -*-
"""MaleFemalePredict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UvYpkfXf7vKWqAOD3FqwYcL1DhzpxgiH
"""

from sklearn.tree import DecisionTreeClassifier

#[height,weight]
features=[ [100,40],[160,60],[165,68],[185,85]]

label=['female','female','male','male']

clf=DecisionTreeClassifier()

trained=clf.fit(features,label)

x=input('enter height in CM ')
y=input('enter weight in KG ')
trained.predict([[x,y]])

